[package]
name = "nightcycle/matrix"
description = "A matrix class!"
version = "1.0.1"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
Vector = "nightcycle/vector@^1.0.2"
